/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;


/**
 *
 * @author ADMIN
 */
public class SignUpFrom extends javax.swing.JFrame {

    private String name;
    private String gioitinh;
    private String ngaysinh;
    private String avatar;
    private DataOutputStream out;
    private DataInputStream in;
    
    /**
     * Creates new form SignUpFrom
     */
    public SignUpFrom(DataOutputStream out, DataInputStream in) {
        this.out = out;
        this.in = in;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_Comtain = new javax.swing.JPanel();
        lblHeading = new javax.swing.JLabel();
        lblHoTen = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        lblGT = new javax.swing.JLabel();
        cmbGT = new javax.swing.JComboBox<>();
        lblNS = new javax.swing.JLabel();
        txtNgaySinh = new javax.swing.JTextField();
        lblTenDN = new javax.swing.JLabel();
        txtTenDN = new javax.swing.JTextField();
        lblMK = new javax.swing.JLabel();
        txtMK = new javax.swing.JPasswordField();
        lblNhaplaiMK = new javax.swing.JLabel();
        txtNhaplaiMK = new javax.swing.JPasswordField();
        btnDangKy = new javax.swing.JButton();
        lblDangNhap = new javax.swing.JLabel();
        btnChonAvatar = new javax.swing.JButton();
        lbl_Avatar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ChatBox");
        setResizable(false);

        Panel_Comtain.setBackground(new java.awt.Color(204, 255, 255));

        lblHeading.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        lblHeading.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-signup-64.png"))); // NOI18N
        lblHeading.setText("Đăng Ký Tài Khoản");

        lblHoTen.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblHoTen.setText("Họ Tên:");

        txtHoTen.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        lblGT.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblGT.setText("Giới Tính:");

        cmbGT.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cmbGT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));

        lblNS.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblNS.setText("Ngày Sinh:");

        txtNgaySinh.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        lblTenDN.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblTenDN.setText("Tên Đăng Nhập:");

        txtTenDN.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        lblMK.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblMK.setText("Mật Khẩu:");

        txtMK.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        lblNhaplaiMK.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblNhaplaiMK.setText("Nhập Lại Mật Khẩu:");

        txtNhaplaiMK.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        btnDangKy.setBackground(new java.awt.Color(255, 255, 255));
        btnDangKy.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnDangKy.setText("Đăng Ký");
        btnDangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangKyActionPerformed(evt);
            }
        });

        lblDangNhap.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        lblDangNhap.setText("Đăng Nhập ==>");
        lblDangNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDangNhapMouseClicked(evt);
            }
        });

        btnChonAvatar.setBackground(new java.awt.Color(255, 255, 255));
        btnChonAvatar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnChonAvatar.setText("Chọn Avatar");
        btnChonAvatar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonAvatarActionPerformed(evt);
            }
        });

        lbl_Avatar.setBackground(new java.awt.Color(255, 255, 255));
        lbl_Avatar.setOpaque(true);

        javax.swing.GroupLayout Panel_ComtainLayout = new javax.swing.GroupLayout(Panel_Comtain);
        Panel_Comtain.setLayout(Panel_ComtainLayout);
        Panel_ComtainLayout.setHorizontalGroup(
            Panel_ComtainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ComtainLayout.createSequentialGroup()
                .addGroup(Panel_ComtainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_ComtainLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(lblHeading))
                    .addGroup(Panel_ComtainLayout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addComponent(btnDangKy, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Panel_ComtainLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(Panel_ComtainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_ComtainLayout.createSequentialGroup()
                        .addGroup(Panel_ComtainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel_ComtainLayout.createSequentialGroup()
                                .addComponent(lblMK)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMK, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Panel_ComtainLayout.createSequentialGroup()
                                .addComponent(lblTenDN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTenDN, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Panel_ComtainLayout.createSequentialGroup()
                                .addComponent(lblNS)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Panel_ComtainLayout.createSequentialGroup()
                                .addComponent(lblGT)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbGT, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Panel_ComtainLayout.createSequentialGroup()
                        .addComponent(lblHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_ComtainLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblNhaplaiMK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNhaplaiMK, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(296, 296, 296))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_ComtainLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(Panel_ComtainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_Avatar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChonAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDangNhap))
                .addGap(69, 69, 69))
        );
        Panel_ComtainLayout.setVerticalGroup(
            Panel_ComtainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ComtainLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel_ComtainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHoTen))
                .addGap(19, 19, 19)
                .addGroup(Panel_ComtainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Panel_ComtainLayout.createSequentialGroup()
                        .addComponent(lbl_Avatar, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnChonAvatar))
                    .addGroup(Panel_ComtainLayout.createSequentialGroup()
                        .addGroup(Panel_ComtainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGT)
                            .addComponent(cmbGT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(Panel_ComtainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNS)
                            .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(Panel_ComtainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTenDN)
                            .addComponent(txtTenDN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(Panel_ComtainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblMK)
                            .addComponent(txtMK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(33, 33, 33)
                .addGroup(Panel_ComtainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNhaplaiMK)
                    .addComponent(txtNhaplaiMK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(btnDangKy, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(lblDangNhap)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel_Comtain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Comtain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblDangNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDangNhapMouseClicked
        try {
            LoginFrom login = new LoginFrom(out, in);
            login.setVisible(true);
            login.setLocationRelativeTo(null);
            this.setVisible(false);
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_lblDangNhapMouseClicked

    private void btnDangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangKyActionPerformed
        
        name = txtHoTen.getText();
        gioitinh = cmbGT.getItemAt(0);
        System.out.println(gioitinh);
        ngaysinh = txtNgaySinh.getText();
        String username = txtTenDN.getText();
        String password = txtMK.getText();
        String NLpass = txtNhaplaiMK.getText();

        if(password.equals(NLpass) == false){
            JOptionPane.showMessageDialog(this, "Mật khẩu không khớp.!!!", "Thông Báo", JOptionPane.WARNING_MESSAGE);            
        }
        
        if(name.equals("") || ngaysinh.equals("") || username.equals("") || password.equals("") || NLpass.equals("")){
            JOptionPane.showMessageDialog(this, "Các trường không được bỏ trống.!!!", "Thông Báo", JOptionPane.WARNING_MESSAGE);
        }
        else{
            try {
                out.writeUTF("Sign up");
                out.writeUTF(username);
                out.writeUTF(password);
                out.flush();
                
                String response = in.readUTF();
                
                if(response.equals("acc da ton tai")){
                    JOptionPane.showMessageDialog(this, "Tài khoản đã tồn tại.!!!", "Thông Báo", JOptionPane.WARNING_MESSAGE);
                }
                
                else{
                    out.writeUTF(name);
                    out.writeUTF(gioitinh);
                    out.writeUTF(ngaysinh);
                    out.writeUTF(avatar);
                    
                    String response1 = in.readUTF();
                    if(response1.equals("signup thanh cong"))
                        JOptionPane.showMessageDialog(this, "Đăng ký thành công. Có thể đăng nhập vào ChatBox.", "Thông Báo", JOptionPane.DEFAULT_OPTION);
                }

            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
        
    }//GEN-LAST:event_btnDangKyActionPerformed

    private void btnChonAvatarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonAvatarActionPerformed
        JFileChooser filechooser = new JFileChooser();
        FileNameExtensionFilter imgFilter = new FileNameExtensionFilter("Hình Ảnh", "jpg", "png");
        filechooser.setFileFilter(imgFilter);
        filechooser.setMultiSelectionEnabled(false);
        int n = filechooser.showDialog(this, "Chọn Ảnh");
        if(n == JFileChooser.APPROVE_OPTION){
            File f = filechooser.getSelectedFile();
            avatar = f.getAbsolutePath();
            ImageIcon icon = EditImage.XuLyAnh.Edit_Img(avatar, lbl_Avatar);
            lbl_Avatar.setIcon(icon);
            
            System.out.println(avatar);
        }
    }//GEN-LAST:event_btnChonAvatarActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(SignUpFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(SignUpFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(SignUpFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(SignUpFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//               SignUpFrom signup =  new SignUpFrom();
//               signup.setVisible(true);
//               signup.setLocationRelativeTo(null);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_Comtain;
    private javax.swing.JButton btnChonAvatar;
    private javax.swing.JButton btnDangKy;
    private javax.swing.JComboBox<String> cmbGT;
    private javax.swing.JLabel lblDangNhap;
    private javax.swing.JLabel lblGT;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblHoTen;
    private javax.swing.JLabel lblMK;
    private javax.swing.JLabel lblNS;
    private javax.swing.JLabel lblNhaplaiMK;
    private javax.swing.JLabel lblTenDN;
    private javax.swing.JLabel lbl_Avatar;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JPasswordField txtMK;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JPasswordField txtNhaplaiMK;
    private javax.swing.JTextField txtTenDN;
    // End of variables declaration//GEN-END:variables
}
